window.AUDIOBOOK_CHAPTERS = [
    {
        "act":  "Act I - The Envoy",
        "title":  "A Song for Leaving",
        "paragraphs":  [
                           "On the morning Gobolin left Kettlehome, the mountain gave him back every sound except the one he wanted.",
                           "The terraces woke beneath a gray spring sky. Hoes struck soil. Goats complained at the milkers. Water hurried through the channels cut by Gobolin\u0027s grandmother, and from the copper sheds came the patient tapping of little hammers. Each noise crossed the valley, touched the steep walls, and returned softened by distance.",
                           "Gobolin stood at the eastern gate with a pack on his shoulders and waited for his mother to sing.",
                           "Sella did not.",
                           "She pulled his cloak straight for the fourth time, inspected the bone toggles, and slapped mud from one sleeve. She was half a head shorter than he was and twice as difficult to move. Three copper rings pierced her left ear. The oldest ring had belonged to her mother, who had worn it on the night Vaerith first came down from the peaks and offered the clans a choice between obedience and extinction.",
                           "Kettlehome\u0027s songs called that night a deliverance. Sella\u0027s private stories called it a negotiation conducted under unfavorable conditions.",
                           "“You packed the red book?” she asked.",
                           "“Between the shirts.”",
                           "“The good shirts?”",
                           "“We have good shirts?”",
                           "She bared a fang at him. It was nearly a smile. “The shirts without soup on them.”",
                           "“Then yes.”",
                           "Behind her, most of the Hearthstone clan had found reasons to work near the gate. Cousins carried the same empty basket back and forth. Old Brik sharpened a hoe that had already become thin enough to shave with. Children watched openly until an aunt hissed at them, whereupon they watched from behind a rain barrel.",
                           "No envoy had gone openly from Kettlehome in three generations.",
                           "Traders went out, of course, but they wore deep hoods and dealt through hill folk who knew when not to ask what lay beyond the old quarry. Vaerith kept his bargains with roads, weather, and rumor. Travelers who came too close found bridges washed out, maps unreliable, and copper-scaled ravens taking unusual interest in their camps.",
                           "Peace had made the valley prosperous. Secrecy had made it small.",
                           "Gobolin touched the leather tube at his belt. Inside lay three sheets of hammered vellum, a map with most of its useful parts omitted, and a trade proposal written in Common, Goblin, and the old angular script favored by dragons. Around his neck hung Vaerith\u0027s treaty-ring: copper twisted into the shape of a laughing mouth.",
                           "It felt heavier than metal should.",
                           "“If the humans refuse,” Sella said, “you come home.”",
                           "“That is one possible instruction.”",
                           "“It is the important instruction.”",
                           "“Vaerith said—”",
                           "“Vaerith has never had a son walk alone into a human town.”",
                           "The work around them became quieter. One did not criticize the dragon loudly. One did not need to. Vaerith heard what was said near copper, in caves, or by anyone who owed him money, which included most of the valley in one fashion or another.",
                           "Sella lowered her voice anyway. “You are not the treaty.”",
                           "“I know.”",
                           "“Say it.”",
                           "“I am not the treaty.”",
                           "“You are not a bridge either. Bridges get walked over.”",
                           "“I am not a bridge.”",
                           "“And you are not required to smile while someone insults you.”",
                           "“That seems contrary to the diplomatic manual.”",
                           "“Then the manual was written by someone with very small teeth.”",
                           "This time he laughed. Sella caught his face between her hands and pressed her forehead to his.",
                           "At last she sang.",
                           "It was only four notes, the opening of the Kettle Song, but the valley knew what to do with them. A hammer answered from the copper sheds. Someone on the upper terraces took the third note and held it. The children joined too early. Old Brik entered in the wrong key, as he had at every funeral, wedding, and planting within living memory.",
                           "The voices did not agree on pitch or timing. They adjusted. The song rolled around the bowl of mountains until Gobolin could no longer pick out his mother\u0027s four notes from all the others.",
                           "He swallowed hard.",
                           "Then the dragon landed on the gatehouse and ruined everything.",
                           "Vaerith of the Verdigris Crown struck the old stones with enough force to shake dust from the arch. He was not the largest of dragons; Gobolin had been reminded of this by Vaerith himself, usually before a detailed account of how size encouraged unimaginative tactics. Even so, his wings covered the gatehouse roof. His scales shone like copper left in rain, green gathering in the seams. One horn had broken near the tip and been capped with gold.",
                           "The singing stopped.",
                           "Vaerith folded his wings. “I dislike farewells.”",
                           "“We noticed,” Sella said.",
                           "The dragon\u0027s golden eyes narrowed with amusement. “They invite promises made under emotional strain. Come here, little ambassador.”",
                           "Gobolin went because one went when a dragon requested proximity. Vaerith lowered his head until one vast eye filled Gobolin\u0027s vision.",
                           "“Tell me your three duties.”",
                           "“Offer copperwork, medicinal moss, and safe passage through the eastern heights. Request recognition of our territory, protection for lawful traders, and formal talks before armed patrols cross the quarry road.”",
                           "“Your private duties.”",
                           "Gobolin hesitated. The eye reflected him perfectly: broad shoulders, scarred green face, yellow traveling cloak, and the battered mandolin case strapped across his pack.",
                           "“Learn whether Rivergate can keep an agreement,” he said. “Learn who profits if it cannot.”",
                           "“And?”",
                           "“Listen for songs about the mountains.”",
                           "Vaerith smiled. A dragon\u0027s smile is not improved by good intentions.",
                           "“Songs reveal what maps conceal. Humans sing of gold where they have found iron, and monsters where they have found someone unwilling to pay tax. Bring me the truth beneath their tune.”",
                           "“You could send one of your ravens.”",
                           "“Ravens are excellent listeners and dreadful negotiators.” Vaerith glanced at the mandolin. “So are many musicians.”",
                           "There it was: the barb tucked inside the blessing.",
                           "Gobolin had not told the dragon he hoped to find a teacher in Rivergate. He had not told anyone except Sella. Yet the College of the Golden Harp appeared in the red book packed between his shirts. Its chapter was marked by a ribbon worn nearly through from handling.",
                           "“If I return with a treaty,” Gobolin said, “may I ask one reward?”",
                           "“You may always ask.”",
                           "“That is not the same as receiving.”",
                           "“You are ready for politics.”",
                           "Vaerith lifted one claw. Pinched between its tips was a small silver bell without a clapper.",
                           "“If the mission fails beyond repair, break this. I will know.”",
                           "“And come for me?”",
                           "“I will know,” Vaerith repeated.",
                           "He set the bell in Gobolin\u0027s palm. The metal was cold enough to ache.",
                           "Then the dragon sprang upward, wings driving rain into everyone\u0027s faces, and circled once above the valley. Copper-wing ravens rose from the cliffs to follow him. For a moment he became only another dark shape beneath the clouds.",
                           "The eastern gate stood open.",
                           "Beyond it, the road entered a cleft in the mountains and vanished.",
                           "Gobolin hugged his mother, bowed to the elders, endured advice from six relatives who had never traveled farther than the western spring, and started walking before courage became another word for delay.",
                           "At the cleft he looked back.",
                           "Kettlehome filled the valley in rings: green terraces, red roofs, steam rising from bathhouses, bright washing on lines. His people had made it beautiful in the shadow of a creature who could burn it all. Perhaps that was why they sang so much. A song occupied the air that fear wanted for itself.",
                           "Sella stood outside the gate. She raised one hand.",
                           "Gobolin raised his.",
                           "Then the road bent, and the mountains swallowed home.",
                           "He walked until the afternoon, when the rain strengthened and the path descended among black pines. His boots filled. The treaty-ring knocked against his chest. Every few miles he practiced the opening of his address.",
                           "“Honored councilors of Rivergate—”",
                           "Too weak.",
                           "“Representatives of the duchy, I come under lawful protection—”",
                           "Too defensive.",
                           "“If anyone reaches for a sword, our dragon will eat your livestock.”",
                           "Accurate, but not ideal.",
                           "He was trying a fourth version when he found blood on the road.",
                           "Not much. Three dark spots diluted by rain. Then a fourth. A boot had slipped in the mud beside them.",
                           "Gobolin stopped singing.",
                           "The pines gave back the hiss of water and nothing else.",
                           "He slid the mandolin case from his shoulder, laid it beneath a tree, and drew the short mountain blade hidden behind it. The road curved around a boulder. Beyond the bend came a scrape, a breath, and a muttered human curse.",
                           "Gobolin advanced.",
                           "A man in a soaked blue surcoat sat against the ditch with one hand clamped above his knee. Blood ran between his fingers. A broken spear lay nearby. He was young, perhaps twenty, with rain-pasted brown hair and the pale, furious expression of someone offended by his own mortality.",
                           "He saw Gobolin and reached for a sword he could not possibly draw in time.",
                           "“Stay back.”",
                           "Gobolin looked at the man\u0027s leg, the spear, and the torn earth leading into the trees.",
                           "“You have been saying that with limited success.”",
                           "“Goblin.”",
                           "“Correct. Human. Now that diplomacy has begun, may I inspect your wound?”",
                           "The man dragged the sword an inch from its scabbard.",
                           "Something moved among the pines behind him.",
                           "Gobolin saw a gray muzzle, low and silent.",
                           "“Do not turn around,” he said.",
                           "“You expect me to—”",
                           "“No. I expect you to continue looking at the frightening goblin while the wolf behind you becomes jealous.”",
                           "The man\u0027s eyes changed.",
                           "Gobolin raised his blade. From the trees came another shape, then a third. These were not starving winter strays. Leather collars circled their necks, each marked with a strip of black cloth.",
                           "Someone had trained them to hunt the road.",
                           "“Can you stand?” Gobolin asked.",
                           "“No.”",
                           "“Can you sing?”",
                           "“What?”",
                           "“Loudly and badly will do.”",
                           "The first wolf stepped onto the road.",
                           "Gobolin drew breath and began the Kettle Song.",
                           "Alone, its four opening notes sounded thin beneath the rain. He stamped the beat with his heel. The wolf\u0027s ears flattened. Gobolin pushed his voice the way he did when calling workers home from the upper terraces. Beauty could wait.",
                           "“Join me,” he told the man.",
                           "“I don\u0027t know it.”",
                           "“Neither does the wolf. Invent something.”",
                           "The man shouted a marching cadence. It had no relationship to Gobolin\u0027s melody, key, or rhythm. Under other circumstances it might have caused an arrest at the Golden Harp.",
                           "Here, it worked.",
                           "Noise filled the road. Gobolin struck the flat of his blade against the broken spear. The man hammered his scabbard on a stone. The wolves hesitated, trained instinct fighting an animal\u0027s distaste for prey that behaved like an approaching army.",
                           "One lunged.",
                           "Gobolin stepped into it. His blade cut the collar, not the throat. The wolf twisted in surprise, landed badly, and fled into the trees trailing black cloth. The others followed.",
                           "For several breaths neither Gobolin nor the human stopped making noise.",
                           "Then the man let his head fall against the bank.",
                           "“That,” he said, “was the worst song I have ever heard.”",
                           "“I intend to study.”",
                           "Gobolin knelt and cut away the torn cloth around the wound. A crossbow bolt had passed through the outer thigh. Painful, bloody, but not immediately fatal if kept clean. He opened his pack for bandages.",
                           "The human watched every movement.",
                           "“Why help me?”",
                           "“Because you are injured.”",
                           "“That isn\u0027t an answer.”",
                           "“It is where I come from.”",
                           "The man looked toward the woods. “There were four of us. We were tracking raiders. They wore goblin arrows.”",
                           "Gobolin tied the bandage tighter than courtesy required. “Arrows are famously loyal to their owners.”",
                           "“You think humans did it?”",
                           "“I think someone put black cloth on trained wolves. I think you were left alive where the road from the mountains could find you. And I think whoever arranged those facts has confidence in the conclusions you prefer.”",
                           "The man\u0027s suspicion did not disappear. It acquired competition.",
                           "“Edric Vale,” he said at last. “Rivergate patrol.”",
                           "“Gobolin of Kettlehome. Envoy.”",
                           "Edric stared at him. Then, despite the wound, the rain, and the wolves, he laughed.",
                           "“Of course you are.”"
                       ]
    },
    {
        "act":  "Act I - The Envoy",
        "title":  "The Road That Watches",
        "paragraphs":  [
                           "They could not remain on the road.",
                           "Edric\u0027s companions might return, but the people who had loosed the bolt might return first. Gobolin recovered his instrument, helped Edric stand, and discovered that the human was substantially heavier than diplomatic theory accounted for.",
                           "They made for an abandoned charcoal burner\u0027s hut marked on Gobolin\u0027s incomplete map. Edric leaned across his shoulders, hopping whenever the injured leg touched earth. By the time the hut appeared between the trees, Gobolin\u0027s knees shook and his prepared address to Rivergate had simplified to a demand for chairs.",
                           "The hut had three walls, half a roof, and a dry corner occupied by a halfling woman eating an apple.",
                           "She wore a brown courier\u0027s coat, green breeches, and enough small leather pouches to suggest either professional organization or an unusually complicated burglary. A crossbow rested across her lap.",
                           "“Afternoon,” she said.",
                           "Edric tried to straighten. “Rivergate patrol.”",
                           "“You should patrol somewhere drier.”",
                           "“We need shelter.”",
                           "“So do I. Fortunately, the hut appears capable of accommodating several social classes.” Her eyes moved to Gobolin, his blade, and the blood on both travelers. “Are we rescuing him or kidnapping him?”",
                           "“Rescuing,” Gobolin said.",
                           "Edric said, “Undecided.”",
                           "The halfling considered this. “I\u0027ll charge the rescue rate until matters clarify.”",
                           "Her name was Pip Thistledown. She carried letters between Rivergate, hill farms, and settlements too small to interest official riders. She also had a fire kit, a tin kettle, and a practical understanding of wounds.",
                           "“Bolt went through,” she said after inspecting Edric\u0027s leg. “Lucky.”",
                           "“It doesn\u0027t feel lucky.”",
                           "“Most luck doesn\u0027t at first. Bad luck is more punctual.”",
                           "While Pip boiled water, Gobolin examined the strip of black cloth cut from the wolf. It was coarse wool, recently dyed. One edge showed three holes where a badge or token had been removed.",
                           "Edric noticed. “The raiders carried a banner like that.”",
                           "“Did you see it?” Gobolin asked.",
                           "“I saw black cloth through the trees.”",
                           "“Did you see goblins?”",
                           "“Small shapes. Bows.”",
                           "Pip poured hot water over a handful of bitter leaves. “Children are small. Halflings are small. Tax collectors become small when viewed from a sufficient distance.”",
                           "Edric scowled. “Three caravans have been hit in six weeks.”",
                           "“Four,” Pip said. “The cooper\u0027s cart never reached Gillian\u0027s Hill.”",
                           "“No report came in.”",
                           "“Dead men are unreliable with paperwork.”",
                           "Gobolin held the cloth near the little fire. The dye had the blue-black sheen of oak gall and iron. Kettlehome used soot-black, which faded gray at the edges. That proved nothing by itself, but it was one more note that did not fit the song.",
                           "“Who benefits?” he asked.",
                           "Edric blinked. “From murder?”",
                           "“From the story told about the murder.”",
                           "Pip smiled around her apple. “He really is an envoy.”",
                           "Outside, rain rattled on the remaining roof. Gobolin thought of Vaerith\u0027s instruction: bring me the truth beneath their tune. He had expected human songs about monsters in the mountains. He had not expected someone to be composing them deliberately.",
                           "Edric accepted the bitter drink. “Captain Tern will want to question you.”",
                           "“I hope he has chairs.”",
                           "“If you walk into Rivergate carrying a goblin treaty after our patrol was attacked—”",
                           "“Then your testimony matters.”",
                           "Edric\u0027s cup stopped halfway to his mouth.",
                           "Gobolin met his eyes. “You do not owe me a lie. Tell them where you found the blood, what you saw, and what I did. Tell them I cut the collar instead of killing the wolf. Tell them the cloth had its badge removed.”",
                           "“You planned this?”",
                           "The accusation stung because it was sensible.",
                           "Gobolin reached slowly into his cloak and removed Vaerith\u0027s ring. He set it on the packed-earth floor. In the firelight, the laughing copper mouth seemed almost alive.",
                           "“This is the seal of Vaerith of the Verdigris Crown,” he said. “If I wanted one wounded patrolman to speak for me, there are easier ways to arrange it. If I wanted war, I would not be carrying vellum.”",
                           "Edric stared at the ring.",
                           "Pip stopped chewing.",
                           "Thunder moved somewhere far off, though the sky had shown no lightning.",
                           "“The dragon is real,” Edric said.",
                           "“Painfully.”",
                           "“And he sent you?”",
                           "“My people sent me. Vaerith permitted the decision, selected the route, revised the terms, supplied the seal, withheld several relevant facts, and will later describe this as freedom.”",
                           "Pip snorted. Edric did not.",
                           "“Why now?” he asked.",
                           "“Because secrecy is failing. Your patrols come farther into the mountains. Our traders need markets. Someone is attacking your caravans and dressing the answer in goblin colors.” Gobolin returned the ring to his neck. “If we do not speak now, others will speak for us.”",
                           "For a long time the rain made the only argument.",
                           "Then came a whistle from the road: two high notes and one low.",
                           "Edric tried to stand. Pip pushed him down and lifted her crossbow.",
                           "“Patrol call,” he said.",
                           "“Can your enemies imitate it?” Gobolin asked.",
                           "“Anyone with lips can imitate it.”",
                           "The whistle came again, closer.",
                           "Gobolin drew his blade. Pip moved beside the doorway. Edric gripped the broken half of his spear.",
                           "A voice called, “Vale?”",
                           "Relief crossed Edric\u0027s face. “Sergeant Nessa!”",
                           "He answered the whistle.",
                           "Three patrol members appeared through the rain. Their bows were ready. At their head came a square-faced woman with iron-gray braids and mud to her thighs. Her gaze found Edric, counted the blood, shifted to Pip, and stopped on Gobolin.",
                           "The bow rose.",
                           "“Drop the knife.”",
                           "Gobolin lowered it carefully to the floor.",
                           "“Sergeant,” Edric said, “he helped me.”",
                           "“Move away from the patrolman.”",
                           "Gobolin moved.",
                           "Pip did not lower her crossbow. “If we\u0027re comparing rescue contributions—”",
                           "“Not now,” Gobolin murmured.",
                           "Sergeant Nessa entered, checked Edric\u0027s wound, and listened to his account without changing expression. When he reached the wolves and the song, one of the patrolmen behind her coughed into his glove.",
                           "“You sang at them,” Nessa said.",
                           "“Tactical singing,” Gobolin said.",
                           "Her eyes were cold. “And you claim to be an envoy.”",
                           "“Diplomatic singing.”",
                           "Pip made a small choking noise.",
                           "Nessa picked up the black cloth, rubbed it between thumb and forefinger, and examined the empty badge holes.",
                           "“Bind the goblin,” she said.",
                           "Edric surged upright and nearly fainted. “Sergeant—”",
                           "“Until Captain Tern hears this, he is either an envoy under seal or the cleverest scout the raiders have sent us. I am not deciding which in a ruined hut.” She looked at Gobolin. “Will you come peacefully?”",
                           "The correct answer, Gobolin knew, was yes. The safe answer was to turn back before Rivergate could close around him. His mother\u0027s voice returned: You are not the treaty. You are not a bridge.",
                           "He looked at Edric, furious and frightened on his behalf. At Pip, measuring windows. At the black strip of cloth in Nessa\u0027s hand.",
                           "Someone had written the first verse of a war and expected everyone else to sing along.",
                           "“I will come under protest,” Gobolin said. “Please record that the protest was eloquent.”",
                           "Nessa tied his wrists in front of him. Not tightly. It was the first courtesy Rivergate offered.",
                           "They left the hut at dusk.",
                           "Pip came because the road ahead was hers anyway, or so she claimed. Edric rode on a litter cut from pine branches. Gobolin walked in the center of the patrol with rain in his eyes and his mandolin on a guard\u0027s back.",
                           "As darkness gathered, he began quietly composing a road song.",
                           "One mile for the promise.",
                           "One mile for the fear.",
                           "One mile for the stranger",
                           "who chose to call you near.",
                           "“That\u0027s terrible,” Edric said from the litter.",
                           "“The second verse improves.”",
                           "“Does it have wolves?”",
                           "“Only if they apologize.”",
                           "Pip supplied a rhyme unsuitable for formal performance. Even Sergeant Nessa smiled at that, though she turned her face before Gobolin could be certain.",
                           "They walked west through the rain, toward a town that had already decided what he was."
                       ]
    },
    {
        "act":  "Act I - The Envoy",
        "title":  "At the Gates of Rivergate",
        "paragraphs":  [
                           "Rivergate rose from the wet plain at noon, all gray walls, red roofs, and chimney smoke pressed low by rain. Gobolin had seen its towers in woodcuts. None had included the line of wagons stranded before the eastern gate or the pikes angled toward him when the patrol approached.",
                           "News moved faster than wounded men. A crowd gathered beneath the gatehouse. Teamsters climbed onto wheels. Children were lifted to shoulders. Gobolin heard raider, dragon, and monster travel through them like sparks.",
                           "Captain Harl Tern came down in a dark cloak. He had a soldier\u0027s square beard and a clerk\u0027s measuring eyes.",
                           "“Sergeant?”",
                           "Nessa reported without ornament. She gave Edric\u0027s account, produced the collar, and named Gobolin\u0027s claim. The captain examined Vaerith\u0027s ring without touching it.",
                           "“An envoy enters unbound,” Gobolin said.",
                           "“An envoy is expected.”",
                           "“Your recent invitations may have gone astray in our secret mountain valley.”",
                           "A few teamsters laughed. Captain Tern did not, but he ordered the rope removed.",
                           "“You may enter under guard until the council meets.”",
                           "“No!” someone shouted.",
                           "A stone struck the mud beside Gobolin. Another hit his shoulder. The crowd surged as fear discovered the pleasure of acting righteous.",
                           "Tern\u0027s guards lowered pikes, but Gobolin raised both empty hands.",
                           "“People of Rivergate!” His valley-call carried beneath the arch. “You have heard that goblins attack your roads. I have heard that humans sharpen swords for our hills. Perhaps both stories are true. Perhaps someone needs them to be.”",
                           "The crowd quieted by degrees.",
                           "“I came carrying terms, not weapons. You owe me no trust. Give me three days. Let me speak before your council and examine the road where your caravan burned. If I flee, Captain Tern may hunt me. If I lie, publish the lie. If I harm anyone under your law, judge me by it.”",
                           "He removed Vaerith\u0027s ring. “But if I prove someone has dressed murder in a goblin face, then hear my people before you march against them.”",
                           "Edric pushed himself upright on the litter. “He saved my life.”",
                           "His voice cracked, but it reached the gate.",
                           "Tern studied Gobolin, then the crowd. “Three days,” he said. “Under my seal and my guard.”",
                           "The gates opened.",
                           "Gobolin entered Rivergate to silence, which was better than stones and not nearly as good as welcome.",
                           "Inside the wall, the silence broke into ordinary commerce. Porters cursed a jammed handcart. A fishwife argued over the weight of a trout. A saw bit through green wood in a nearby yard. Gobolin had spent the journey imagining Rivergate as one great human opinion. The town paid him less attention than that. A hundred private concerns crossed the street without waiting to decide what he was.",
                           "Captain Tern assigned Sergeant Nessa to escort him. She returned his knife but kept the mandolin, explaining that the treaty protected an envoy, not the envoy\u0027s luggage. Gobolin objected until he saw a boy on a doorstep miming the way he bared his teeth when angry.",
                           "He closed his mouth.",
                           "At the market square, a butcher refused to let them pass beneath his awning during a fresh downpour. The baker next door waved them in, then charged Gobolin twice the posted price for a heel of yesterday\u0027s loaf. Nessa watched him pay.",
                           "“You could appeal to the watch,” she said.",
                           "“Would the watch refund one copper?”",
                           "“Probably not.”",
                           "“Then I have purchased useful information.”",
                           "The bread was hard enough to support masonry. He ate it anyway. By the time they reached the Bent Nail, the story of the goblin at the gate had acquired a dragon overhead, six murdered guards, and a wagon full of human bones. None of the versions mentioned Edric\u0027s testimony.",
                           "Gobolin understood then that his three days were not merely time allowed for investigation. They were three days in which Rivergate would write him faster than he could answer."
                       ]
    },
    {
        "act":  "Act I - The Envoy",
        "title":  "The Bent Nail",
        "paragraphs":  [
                           "Captain Tern quartered Gobolin at the Bent Nail because its owner owed the watch a favor and its furniture was already damaged.",
                           "The inn stood near the tanners\u0027 lane. Its sign depicted a nail bent into a smile. Inside, laborers drank beside caravan guards, and every conversation stopped when Gobolin crossed the threshold.",
                           "The innkeeper, Mara Venn, looked him over. “Pay in advance. No frightening guests after midnight.”",
                           "“May I frighten them before midnight?”",
                           "“Within reason.”",
                           "Pip took the smallest room at the cheapest rate. Edric went to the garrison infirmary after promising to return for the council hearing. Sergeant Nessa posted two bored guards outside.",
                           "In the common room, a half-orc played a viol near the hearth. He was enormous, with moss-green skin and a broken tusk. His bow moved gently enough to make the room\u0027s suspicion seem crude.",
                           "The tune did not quiet the room. It worked beneath it, fitting itself between dice cups and spoons, altering the noise without demanding that anyone notice. Gobolin had practiced music as an announcement: listen, I have learned this; listen, I might belong. Moss appeared content to let a melody change the shape of an evening anonymously.",
                           "Gobolin listened until the piece ended.",
                           "“The third phrase comes from the north,” he said.",
                           "The musician nodded.",
                           "“But the ending is a river lament.”",
                           "Another nod.",
                           "“I am Gobolin.”",
                           "“Moss.”",
                           "That exhausted Moss\u0027s interest in introduction.",
                           "Gobolin bought stew and listened. A wool merchant blamed mountain goblins for three lost wagons. A drover swore the attackers had human boots. A cooper\u0027s widow said the watch ignored her husband\u0027s disappearance because Lady Merrow\u0027s cargo had burned the same night. At the wealthy tables, every loss was an attack on trade. At the poor ones, every loss had a name.",
                           "Moss played through all of it.",
                           "Later, he sat opposite Gobolin without invitation. “Black Banner.”",
                           "Gobolin waited.",
                           "“Saw them years ago. Goblin mercenaries. Their badge is three iron teeth.” Moss tapped the holes in the cloth. “Removed here so witnesses invent their own badge.”",
                           "“Why tell me?”",
                           "“You listened before asking me to speak.”",
                           "Pip appeared with three mugs. “Also, Lady Merrow\u0027s consortium bought every warehouse near the east quay this winter. If the hill road closes, river freight triples.”",
                           "“How do you know?”",
                           "“I deliver bills to people who cannot imagine couriers read.”",
                           "The inn door opened. A gnome in a blue academic coat stepped inside, shook rain from a silver-tipped cane, and frowned at the company.",
                           "Mara hurried to him. “Master Gongo. Your usual?”",
                           "Gobolin nearly dropped his mug.",
                           "Master Gongo of the Golden Harp looked exactly like the portrait in Gobolin\u0027s red book, except older, smaller, and substantially less pleased by the world.",
                           "Gobolin stood. “Master, my name is—”",
                           "“I know who you are. Half the town has discovered the news, embroidered it, and sold copies.” Gongo\u0027s gaze settled on the mandolin case. “You wish to study.”",
                           "“How could you know that?”",
                           "“No one carries an instrument that carefully unless it contains either music or explosives. Your posture suggests the former.”",
                           "“Will you hear me?”",
                           "“No.”",
                           "The answer arrived without cruelty, which made it worse.",
                           "Gongo accepted his drink. “The college is not a sanctuary for interesting political problems. Resolve your embassy. Survive the week. If you still desire instruction when the attention has moved elsewhere, knock on our door like any other applicant.”",
                           "“And will it open?”",
                           "“That depends on what you play.”",
                           "Gongo left with his drink and no further explanation.",
                           "Moss lifted her bow. “Not no.”",
                           "“It sounded remarkably like no.”",
                           "“Wrong rhythm,” Moss said, and began the river lament again.",
                           "That night Gobolin lay awake in a room with a ceiling too low for comfort. Every cart on the lane sounded like boots stopping outside. He placed Vaerith\u0027s bell on the table, moved it to the windowsill, then hid it in his boot. The dragon had offered rescue without promising it, a gesture perfectly balanced between care and control.",
                           "Below, Moss continued playing after the paying guests had gone. The river lament repeated, but never quite the same way. Gobolin carried his mandolin downstairs.",
                           "Moss did not invite him to join. Gobolin joined anyway and entered too loudly. Moss changed key to accommodate him. On the next repetition Gobolin tried to anticipate the change and missed it. After the third, Moss stopped.",
                           "“You listen for where you can enter,” he said.",
                           "Gobolin waited for the rest.",
                           "“Listen for where the tune needs room.”",
                           "They began again. Near dawn, Gobolin managed eight measures without trying to prove he was there."
                       ]
    },
    {
        "act":  "Act I - The Envoy",
        "title":  "Terms of Peace",
        "paragraphs":  [
                           "The council chamber smelled of wool, wet cloaks, and old authority. Duchess Elira sat beneath Rivergate\u0027s green banner, young enough that every older councilor explained her own town to her.",
                           "Lady Merrow Vale occupied the merchant bench. She was silver-haired and composed, her black gloves spotless despite the weather.",
                           "Gobolin presented Kettlehome\u0027s offer. Copperwork and medicines. Safe passage through the eastern heights. Recognition of borders. Protection for lawful traders. Talks before troops crossed the quarry road.",
                           "The council listened politely until he named Vaerith. Then a miller from the lower ward asked what treaty could bind a creature able to cross the walls in a single flight. A temple delegate wanted to know who would answer for a goblin crime committed beyond Rivergate\u0027s reach. These were harder questions than insults because Gobolin had asked versions of them himself.",
                           "“So the dragon owns your valley,” Lady Merrow said.",
                           "“He would say he protects it.”",
                           "“What would you say?”",
                           "“That protection becomes ownership when only one party defines the danger.”",
                           "The duchess leaned forward. Merrow\u0027s smile tightened.",
                           "“You see the difficulty,” Merrow said to the room. “An armed enclave controls an unmapped pass within three days of our farms. It asks us to recognize borders we have not surveyed, under the protection of a dragon who answers to no court. Caution is not prejudice.”",
                           "Several councilors nodded. Gobolin disliked her argument because parts of it were sound.",
                           "“And yet you bear his seal,” she said.",
                           "“I bear my clan\u0027s words.”",
                           "Edric entered on a crutch and testified. Sergeant Nessa showed the black cloth. Moss identified the missing badge. Pip described the freight purchases, though Merrow dismissed them as normal preparation for troubled roads.",
                           "“Speculation,” Merrow said. “Meanwhile, our people die.”",
                           "“Then let me investigate,” Gobolin replied. “Send your guards. Send your clerk. If the trail points to Kettlehome, I will walk back in chains.”",
                           "The duchess called for a recess. Arguments broke across the chamber. The council did not return that afternoon. Its clerks spent the next two days verifying Vaerith\u0027s seal, interviewing Edric without Gobolin present, and taking statements about the missing caravans. Gobolin remained at the Bent Nail, where suspicion lost its novelty but not its force.",
                           "On the third morning, Elira gave him two days in the field and an escort. Captain Tern would choose the site. Any evidence belonged to the duchy. The treaty would wait.",
                           "Gobolin should have been pleased. Instead he heard the conditions that remained unspoken. If he found nothing, the council lost only two days. If he found goblin guilt, he had volunteered to return in chains. If he found human guilt, Rivergate retained custody of the proof. The arrangement risked almost nothing that belonged to the people granting it.",
                           "“I request one addition,” he said. “A representative chosen by the families of the dead.”",
                           "Lady Merrow objected first. “Grief is not an investigative qualification.”",
                           "“Neither is commerce.”",
                           "The duchess suppressed a reaction and asked the families to name an observer. They chose the cooper\u0027s widow, Lysa Harrow, who declined to travel but insisted that Pip carry a tablet with the names of every missing driver. Gobolin watched Merrow note the tablet and understood that names could inconvenience a story built from cargo totals.",
                           "Outside, Lady Merrow caught up with him beneath the arcade.",
                           "“You speak well,” she said. “Better than those who sent you expected, I imagine.”",
                           "“My mother expected perfection. Vaerith expected usefulness.”",
                           "“And what do you expect?”",
                           "“A question hidden inside a compliment.”",
                           "Merrow laughed. “Rivergate rewards adaptable people. If your valley truly wants trade, it will need a partner who understands markets. Bring me exclusive rights to your copper, and many fears could be calmed.”",
                           "“Whose fears?”",
                           "“The ones with votes.”",
                           "She left him with the faint scent of lavender and iron.",
                           "Pip emerged from behind a pillar. “Was that a bribe?”",
                           "“Not yet. It was tuning.”",
                           "He regretted the phrase as soon as he said it. Pip gave him the look reserved for people who mistake an image for an answer.",
                           "“It was an offer,” he amended. “If I make Merrow the only door between the valley and this town, she will arrange to own both sides of the threshold.”",
                           "“Better.”",
                           "“Do you grade everyone?”",
                           "“Only people who speak like pamphlets.”"
                       ]
    },
    {
        "act":  "Act I - The Envoy",
        "title":  "A College with Closed Doors",
        "paragraphs":  [
                           "The College of the Golden Harp occupied a narrow stone house behind the temple square. Its golden door knocker was shaped like an ear.",
                           "Gobolin knocked before the expedition left at dawn.",
                           "Gongo opened in a sleeping cap. “Your political emergency has not ended.”",
                           "“It may end me tomorrow. That complicates waiting.”",
                           "Inside, students practiced scales behind closed doors. Gobolin smelled ink, wax, old wood, and the particular dust of books kept above kitchens.",
                           "Gongo led him to a bare teaching room. “One piece.”",
                           "The walls bore the pale rectangles of pictures recently removed. Gongo noticed Gobolin looking.",
                           "“The governors prefer the college avoid appearing to endorse your embassy.”",
                           "“You took down portraits for that?”",
                           "“They took down their names. I removed the frames before they damaged them.”",
                           "The distinction mattered to Gongo, though Gobolin did not yet understand why.",
                           "Gobolin unpacked his mandolin. He had planned to play a court air copied from the red book, technically difficult and emotionally empty. Instead he played the road song.",
                           "One mile for the promise.",
                           "One mile for the fear.",
                           "He added Edric\u0027s marching rhythm, Pip\u0027s indecent rhyme transformed into a respectable reference to turnips, and the descending phrase Moss had played at the Bent Nail. The melody stumbled where the voices met. He stopped.",
                           "“Unfinished,” Gongo said.",
                           "“The road is unfinished.”",
                           "“Convenient.”",
                           "Gongo took the mandolin, adjusted one tuning peg, and returned it. “Your right hand rushes when you are afraid. You imitate three traditions and understand one. Your rhyme depends on ‘near’ twice.”",
                           "Gobolin\u0027s ears burned.",
                           "“But?”",
                           "“A student who demands a ‘but’ after criticism is collecting praise, not instruction.” Gongo opened the door. “Return when the song has an ending.”",
                           "“Is that an admission test?”",
                           "“It is a condition under which I will tolerate hearing it again.”",
                           "Gobolin packed the mandolin more roughly than it deserved. “Would the answer be different if I were human?”",
                           "Gongo rested both hands on his cane. “Yes.”",
                           "The admission struck harder than a denial.",
                           "“A human applicant can fail privately,” the gnome continued. “If I admit you today, patrons will call it politics. Other students will use you to prove their tolerance or their suspicion. Every poor performance becomes evidence about goblins; every success becomes evidence of my virtue. You asked to study music. I do not yet know whether this college can allow you to do that.”",
                           "“So you protect me by keeping me out.”",
                           "“No. I protect the college by keeping you out. Do not improve my motives for me.”",
                           "Gobolin looked down at the golden ear worked into the door handle. He had imagined institutions as doors because doors could open. Gongo was telling him the building beyond might remain unchanged and call the opened door generosity.",
                           "“Then what would make you admit me?”",
                           "“Music strong enough that refusing it costs us more than changing.”",
                           "Gobolin stepped into the hall.",
                           "“Envoy,” Gongo said behind him. “The black cloth was dyed with oak gall and echo-iron.”",
                           "Gobolin turned.",
                           "“You know the ore?”",
                           "“I know enough to fear anyone mining it without understanding what answers when it sings.” Gongo closed the teaching-room door. “Ask your dragon what lies beneath your valley.”",
                           "At the eastern gate, Captain Tern waited with Nessa, Edric, Pip, and Moss. Moss carried her viol and a caravan sword. She had invited herself, and the others had made room.",
                           "The rain had finally stopped. Beyond the walls, the trade road shone beneath a pale strip of morning.",
                           "Gobolin touched Vaerith\u0027s ring, heard Gongo\u0027s warning, and understood that he had been sent to uncover human secrets by a dragon who had kept one of his own.",
                           "“Ready?” Pip asked.",
                           "“No.”",
                           "She grinned. “Best time to leave.”",
                           "They passed through the gate and took the road east."
                       ]
    },
    {
        "act":  "Act II - The Broken Accord",
        "title":  "Ash on the Trade Road",
        "paragraphs":  [
                           "The burned caravan lay nine miles east of Rivergate. Rain had flattened the ash but not erased the attack. Two wagons blocked the road nose to nose. A third had burned in the ditch.",
                           "“Ambush from the north,” Edric said.",
                           "Pip pointed at wheel ruts leaving south. “Made to look that way. The valuable wagon departed.”",
                           "Moss found a black-fletched arrow beneath a body. Its stone head was tied with valley cord. She knew the dead driver, a woman called Hara who had once hired her for the winter run to Highharbor. Moss had left her caravan after passengers complained that an armed half-orc frightened their children. Hara had paid her for the full season anyway.",
                           "He covered her face before he examined the arrow.",
                           "“Kettlehome,” Gobolin said. “But the knot is wrong. We bind clockwise because the twist holds when wet.”",
                           "They followed the southbound ruts to an abandoned lime quarry. Inside waited six men, two goblins, and the wolves from the road.",
                           "The fight began before conversation. Nessa\u0027s shield caught a bolt. Moss drew the sword hidden beneath her viol. When one quarryman tried to surrender, Moss struck him hard enough to split his lip and raised the blade again. Edric caught her wrist.",
                           "“Alive,” Edric said.",
                           "Moss stared at the man, then at the road where Hara lay. She lowered the sword. Pip, already behind a stone cart, kicked the quarryman\u0027s dropped knife into the lime pit.",
                           "Gobolin faced a goblin wearing three iron teeth.",
                           "“Black Banner?” he called.",
                           "“Mountain pet.”",
                           "“Whose pet wears a human collar?”",
                           "Rage spoiled the raider\u0027s aim. Gobolin disarmed him and caught his jaw before he could bite the black pellet hidden behind a molar. For one hopeful second, the raider might have lived to speak. Then an arrow came from the rear passage and struck beneath his shoulder blade. His own side had silenced him.",
                           "He died staring at Vaerith\u0027s ring, one hand gripping Gobolin\u0027s sleeve. “Ruk said no children,” he whispered in Goblin. “Tell him they burned the cooper\u0027s boy.”",
                           "The admission complicated the dead man at once. He had helped attack a caravan; he had also believed there were limits. Gobolin closed his eyes before Nessa could ask for a translation.",
                           "The locked chest held valley cord and a sheaf of warehouse tallies. The pages named no owner. Each shipment was identified by a double crescent, a common factor\u0027s mark used by half a dozen trading houses along the river. Pip turned the papers over and found pinholes in their upper corners.",
                           "“Merrow\u0027s countinghouse binds its copies with four pins,” she said. “These had three.”",
                           "Nessa looked unimpressed. “Then they came from someone who owns string and three pins.”",
                           "Gobolin had hoped for a seal, a signature, anything he could place on the council table and call truth. Instead they had goods that might have been stolen and papers that proved only that somebody kept accounts. He had built his case aloud before the evidence could bear it. Now the others were waiting for him to admit as much.",
                           "“This proves preparation,” he said. “It does not prove who prepared it.”",
                           "Edric glanced toward the dead raider. “That distinction won\u0027t help him.”",
                           "Thunder rolled above the eastern peaks. Moss touched the quarry wall. It hummed under her palm."
                       ]
    },
    {
        "act":  "Act II - The Broken Accord",
        "title":  "The Voice Beneath the Bridge",
        "paragraphs":  [
                           "Their human prisoner gave his name as Kest. He gave no others.",
                           "On the return road, the old stone bridge began to sing. Every nail in the wagon sounded the same high note. Kest screamed. Blood ran from his nose, and words poured from him in a voice deeper than his own.",
                           "“Bring the mouth to the hollow. Bring the keeper\u0027s song.”",
                           "Gobolin seized him. “Who paid you?”",
                           "“The lady in black gloves. The lady beneath the bell.”",
                           "The note stopped. Kest collapsed.",
                           "Under the bridge, Pip found a sliver of dark metal that vibrated when Gobolin spoke. Back in Rivergate, Captain Tern locked Kest under guard. By sunset, the prisoner was dead. The official report said heart failure. Edric had seen bruises around his throat.",
                           "The report waited on Tern\u0027s desk with a sand shaker resting across one corner. Edric read it twice. His injured leg had stiffened during the ride. By the final line, his grip had creased the paper.",
                           "“Lieutenant Ors examined the body?” he asked.",
                           "Tern remained standing at the window. In the yard below, watchmen changed shifts. “He was the ranking officer present.”",
                           "“Ors ordered us north after the raiders. They were south. Ors knew which cell held Kest.”",
                           "“Careful.”",
                           "Edric\u0027s hand closed around the paper. “I was careful when I repeated what he taught me. Goblin arrows. Goblin country. Goblin raiders. If Gobolin hadn\u0027t found me, I would have died certain I understood what happened.”",
                           "The page tore between his hands. Tern turned from the window then, anger plain on his face, though Gobolin could not tell whom it was for.",
                           "“You are a patrolman, Vale. You bring facts to your captain. You do not choose the guilty man because the choice hurts.”",
                           "Edric laid the two halves on the desk. “Then investigate the bruises.”",
                           "Outside the watch house, he was sick in the gutter. Gobolin waited a few paces away. Comfort seemed presumptuous; silence felt like punishment. In the end he held Edric\u0027s crutch while the human wiped his mouth.",
                           "“You knew the knot was wrong immediately,” Edric said.",
                           "“Yes.”",
                           "“I saw what I had been taught to see.”",
                           "“So did I, at the gate. I expected every person there to hate me. Some were only waiting for their wagons to move.”",
                           "Edric did not ask to be forgiven. He reclaimed the crutch and started toward the college.",
                           "They took the metal to Gongo, who locked the college doors before unwrapping it.",
                           "“Echo-iron,” he said. “It stores patterned vibration and reinforces whatever pattern follows. It cannot think, speak, or invent a command. Give it one voice often enough, though, and it will return that voice long after the singer has gone.”",
                           "“Where did you find it?” Gobolin asked.",
                           "Gongo looked at Vaerith\u0027s ring. “In the eastern mountains. Your dragon burned my maps.”",
                           "The gnome fetched three tuning forks from a cabinet. He struck the first against his knee and held it near the wool-wrapped sliver. Nothing happened. The second made the metal creep a finger\u0027s width across the table. At the third, Kest\u0027s borrowed words emerged in a thin metallic murmur: bring the mouth.",
                           "Pip backed into a bookshelf.",
                           "“It remembered him,” Gobolin said.",
                           "“It remembered pressure in the air. Meaning belongs to us.” Gongo damped the fork. “That distinction matters. Echo-iron cannot devise a spell, but it can repeat one without tiring. A binding that should require a choir for one minute can continue for hours if the chamber has learned it.”",
                           "Moss unwrapped her viol and played the first phrase of the river lament. The sliver answered one beat late. When she changed the final note, it repeated the old ending.",
                           "“Slow learner,” Moss said.",
                           "“Stubborn learner,” Gongo corrected. “It favors what it has heard most.”",
                           "Gobolin thought of the stories repeated along the trade road until fear no longer required evidence. “So do towns.”",
                           "Gongo gave him a sharp look. “Do not turn mineral behavior into a speech. Learn the limitation. Novelty weakens it. Repetition gives it force.”"
                       ]
    },
    {
        "act":  "Act II - The Broken Accord",
        "title":  "Three Honest Lies",
        "paragraphs":  [
                           "Suspicion would not hold Lady Merrow. They needed records, witnesses, or goods that could be traced to her. Gobolin also carried the raider\u0027s last words and had told no one. He called the omission caution: Ruk\u0027s name would turn the council toward war before it explained anything. In truth, Ruk was clan, however estranged, and Gobolin wanted one fact that had not already become Rivergate property.",
                           "For four days the investigation produced paper. Pip led him through countinghouses where clerks licked their fingers before turning pages and regarded questions as a contagious expense. Moss waited outside; owners who tolerated a goblin envoy became suddenly attentive when a half-orc entered behind him. Edric used his badge to request customs copies and learned how many ways a public office could say tomorrow.",
                           "At Hollis and Sons, the senior clerk knew Pip\u0027s family name. He pulled a foreclosed farm account from an older shelf and laid it beside the shipping books they had requested.",
                           "“Thistledown debt remains unpaid,” he said. “Couriers handling confidential records require unencumbered guarantors.”",
                           "Pip\u0027s face became pleasantly blank. “The farm paid three times what my father borrowed.”",
                           "“Interest is also a debt.”",
                           "Gobolin expected her to produce one of the sharp answers she kept ready for authority. She returned the ledger instead. Outside, she walked two streets before speaking.",
                           "“This is why I read the letters,” she said. “People write theft in columns and call it arithmetic.”",
                           "She went back alone that evening. Gobolin did not ask how she obtained Hollis\u0027s customs copies. He did, however, copy the words unencumbered guarantor into the margin of Kettlehome\u0027s draft trade agreement and draw a line through them.",
                           "The quarry tallies matched three shipments unloaded at Merrow\u0027s east warehouse, but the goods had been entered as broken agricultural tools. Their weights were wrong for ploughs and right for mining tackle. It suggested fraud. It did not connect Merrow to the dead caravans.",
                           "On the fifth morning, Gobolin told the guild committee that Kettlehome intended to choose one factor for its first trading season. That much was authorized. He added that any house concealing attacks on the road would be excluded. The guildmaster heard a commercial opportunity and sent a clerk to compare competitors\u0027 manifests before lunch.",
                           "Gobolin next told Captain Tern that the quarry records implicated someone with access to the council\u0027s reports. He did not claim to have a name, though Tern understood him to mean that he did. The captain quietly doubled the evidence guard. That evening his lieutenant tried to enter the locked room with a copied key.",
                           "The third conversation took place in Lady Merrow\u0027s winter garden. Bare vines clicked against the glass while she poured tea for Gobolin and left Pip standing.",
                           "“The valley will discuss the legal status of echo-iron,” he said.",
                           "“With whom?”",
                           "“With anyone prepared to recognize that Kettlehome owns what lies beneath it.”",
                           "“Your dragon owns it. You said as much in the council.”",
                           "“I said he controls it. Ownership is precisely what requires discussion.”",
                           "He let her assume Vaerith had authorized the offer. The omission left a sour taste stronger than the tea. Vaerith often built lies from accurate pieces. Gobolin had learned the method faster than he cared to admit.",
                           "Merrow did not confess or threaten him. She argued that no town should leave a strategic substance under the private control of a dragon, and Gobolin agreed more often than he wished. Only when he mentioned that other houses might bid did her composure narrow into calculation.",
                           "An hour later, a rider left Merrow\u0027s stable with a hymn book sewn inside his coat. Pip knew the boy who swept the stable and paid him more than Gobolin thought the information worth. They intercepted the rider outside the tannery without drawing steel.",
                           "The message used dockside bookkeeping phrases rather than names: The new buyer has sampled the eastern stock. Move the old appraiser before the third bell. Begin the deep inventory.",
                           "Gobolin read it beneath a street lamp while rain spotted the paper. “The new buyer may be me. The old appraiser is probably Gongo.”",
                           "“Probably is enough to run on,” Pip said.",
                           "The third bell began as they crossed the square. Halfway through its second stroke, the college windows burst outward."
                       ]
    },
    {
        "act":  "Act II - The Broken Accord",
        "title":  "The Dragon\u0027s Price",
        "paragraphs":  [
                           "They found Gongo alive beneath a bookcase, but the attackers had taken his research and three students. A message scarred the floor: BRING THE ENVOY TO THE LISTENING CAVES.",
                           "The duchess searched Merrow\u0027s empty house. The public ledgers were immaculate. In a locked cabinet her clerks found contracts for pumps, lifting tackle, and ore carts routed through three shell partnerships. None named the Black Banner. Together with the quarry tallies, they established a concealed mining venture; they still did not prove murder.",
                           "Gobolin broke Vaerith\u0027s silver bell.",
                           "The dragon arrived after midnight. He demanded privacy; Gobolin refused.",
                           "The courtyard was too small for him. One wing pressed against the rain gutter, and his tail lay across the herb beds the students had planted in spring. Gongo stood beneath the covered walk with his arm in a sling. Pip had positioned herself near a kitchen door. Moss remained in the open, which Gobolin suspected was her way of refusing to be arranged by fear.",
                           "“You hid echo-iron beneath our homes,” Gobolin said. “You sent me to repair the danger without naming it.”",
                           "“Had Rivergate known, armies would already be in your valley.”",
                           "“Had I known, I might have seen the trap before people died.”",
                           "“I protected Kettlehome for seventy years.”",
                           "“And ensured it could not survive one year without you.”",
                           "Silence became enormous.",
                           "Gobolin had imagined confronting Vaerith many times. In those private rehearsals he had always found the sentence that stripped the dragon of certainty. The actual creature smelled of rain, hot metal, and the goats he had eaten on the flight. His anger was not a metaphor. If Vaerith lost control, people in neighboring houses would die before Gobolin finished being correct.",
                           "His knees wanted to bend. He kept them straight. Sella would eventually hear every detail, including his posture.",
                           "At last Vaerith said, “Echo-iron magnifies a dragon\u0027s binding-name. Merrow has Gongo\u0027s research and goblins who know the lower paths.”",
                           "“Ruk,” Gobolin said. His cousin had left Kettlehome seven years earlier, furious that peace required kneeling to a dragon.",
                           "Vaerith\u0027s gaze confirmed it.",
                           "He offered to destroy the caves, though it would collapse part of Kettlehome.",
                           "Gobolin had no plan, not yet. He had spoken as if he did because everyone in the courtyard—the wounded students, his companions, even the dragon—was looking at him. The old desire to sound worthy had survived every lesson Rivergate offered.",
                           "“You will wait,” he said. “I need an hour, and I need you not to solve this by burning the part that frightens you.”",
                           "Vaerith lowered his head until the broken horn nearly touched Gobolin\u0027s chest. “One hour.”",
                           "They used it badly. Gongo\u0027s first proposal required six trained singers they did not have. Captain Tern wanted troops on the road before dawn; Vaerith said armed humans would unite every hostile clan in the mountains. Pip suggested entering through the drainage galleries and learned that a century of mineral springs had made them impassable. Edric fell asleep in his chair and woke ashamed.",
                           "Moss drew a rough map from memory of caravan routes. “Not an army,” she said. “A company.”",
                           "That became the beginning. Five travelers could cross without looking like an invasion. Vaerith would remain above the peaks, close enough to intervene and far enough not to trigger the binding. Kettlehome would have to decide its own defense after Gobolin explained what had been hidden from it.",
                           "“They may refuse us,” Gobolin said.",
                           "“Then we return,” Gongo replied.",
                           "Vaerith\u0027s claws scored the paving. “You would leave me bound?”",
                           "“If the alternative is destroying their home without their consent,” Gobolin said, “yes.”",
                           "The dragon glanced toward Gongo, then the college windows. He had expected refusal from enemies. Gobolin\u0027s conditional loyalty left him without a practiced response."
                       ]
    },
    {
        "act":  "Act II - The Broken Accord",
        "title":  "The Night of Broken Strings",
        "paragraphs":  [
                           "Merrow\u0027s remaining agents struck before dawn, burning the Bent Nail while disguised men attacked the college again. Moss held the stair. Pip led students across the roofs. Edric fought his former lieutenant and emerged with the watchman\u0027s confession.",
                           "In the music hall, an attacker raised a hammer over Gongo\u0027s hands.",
                           "Gobolin threw his mandolin. It struck the man\u0027s wrist and shattered against the wall. Moss reached him a moment later.",
                           "When the fires were contained, Gobolin knelt among splintered maple and loose strings. The instrument had belonged to Sella\u0027s brother.",
                           "He tried to fit the neck back into the body. The break was jagged, absurdly clean in one place and crushed in another. A loose string had wound around his thumb. He remembered his uncle letting him pluck it at six years old, then at eight, then refusing at nine because Gobolin had left it near the soup hearth. Years later, when the instrument became his, Gobolin had mistaken inheritance for evidence that he deserved it.",
                           "Around him, students swept glass. One was crying without sound. Gongo\u0027s broken fingers had already swollen purple. The attack had failed, yet the room looked like failure.",
                           "Gongo sat beside him, two fingers broken. “An instrument is not the music.”",
                           "“Teachers say that because they do not pay for instruments.”",
                           "Gongo produced a travel lute saved from the archive. “Mine, when I believed roads taught more than libraries.”",
                           "“And now?”",
                           "“Now I believe a student should return it.”",
                           "Gongo had not admitted him. He had trusted him with something more useful than a place on the rolls.",
                           "Gobolin closed the case without touching the lute. “I lied to Tern. I let Merrow believe Vaerith had authorized terms he had never heard. And a dying Black Banner raider named Ruk to me. I kept it from all of you.”",
                           "Pip stopped sweeping. Edric\u0027s face hardened first; he had spent the day demanding honesty from his own captain.",
                           "“Why?” Gongo asked.",
                           "“Because I wanted to be the person who knew what to do with it.”",
                           "The room stayed quiet. Moss eventually placed the travel lute case in Gobolin\u0027s hands. “Tell them now.”",
                           "So he did. By morning Captain Tern knew, then Duchess Elira, then the council. The delay cost Gobolin their confidence precisely when he needed freedom to leave."
                       ]
    },
    {
        "act":  "Act II - The Broken Accord",
        "title":  "Outlaw Music",
        "paragraphs":  [
                           "The council forbade Gobolin to leave while Merrow\u0027s allies demanded a trial. Even members who believed him had cause: he had concealed a material witness statement, misrepresented his authority, and helped provoke Merrow into action inside the town. Duchess Elira privately warned that legal delay would last until the valley fell.",
                           "So the envoy escaped under her official prohibition, using a gate key she accidentally left on the table.",
                           "Pip brought routes and provisions. Moss brought her viol. Edric set his badge on Captain Tern\u0027s desk.",
                           "Tern pushed it back. “Bring it home when it means what it should.”",
                           "Gongo came despite his bound hand. “Merrow needs my voice to shape the binding. I know how to break it.”",
                           "At the east gate, twenty townspeople waited: Bent Nail regulars, college students, guild clerks, and the cooper\u0027s widow.",
                           "“You cannot all come,” Gobolin said.",
                           "“We know,” the widow replied. “We\u0027re walking the first mile.”",
                           "She carried no weapon, only a rain cloak and a small wooden tablet carved with her husband\u0027s name and her son\u0027s. The second name answered the raider\u0027s last words. Gobolin had expected anger when he told her; she had given him a silence more difficult to endure.",
                           "“My boy rode with the cooper because the road was supposed to be safer than the river,” she said. “If those hills are where people decided he counted as freight, I want one part of the road to remember otherwise.”",
                           "They sang the road song. Each supplied a line. Most were poor. One did not rhyme. Gongo complained until his voice cracked.",
                           "At the milestone the townspeople stopped. Gobolin\u0027s company continued east: a goblin envoy, a halfling courier, a half-orc musician, a guardsman, and a gnome teacher with broken fingers.",
                           "Behind them, Rivergate kept singing. Ahead, the mountains answered with thunder.",
                           "They traveled for three days. Vaerith remained somewhere above the cloud cover, visible only when lightning outlined a wing. On the first night, Edric discovered that his badge did not make him competent at finding dry firewood. On the second, Gongo\u0027s injured hand developed a fever. They lost half a day while Pip found willow bark and Moss boiled the bandages.",
                           "Gobolin resented the delay, then hated himself for it. Hostages waited in the mountain. So did his mother. Gongo\u0027s fever still required time. Merrow had treated other people\u0027s pain as a cost she could enter in a ledger; Gobolin would not begin copying her arithmetic now.",
                           "Near the old quarry road, they found a Black Banner lookout barely older than the children at Kettlehome\u0027s gate. He dropped his bow and surrendered. Edric wanted to bind him. Pip argued that a missing sentry would warn the others more quickly than a frightened one returning late.",
                           "Gobolin questioned him in Goblin. Ruk had promised land in the valley after Vaerith fell. Merrow had promised tools and legal recognition from Rivergate. The sentry knew nothing of burned caravans. He had joined because his little sisters were sleeping in a chalk pit outside Stonecross.",
                           "“Tell Ruk I am coming,” Gobolin said.",
                           "The others stared at him after the boy vanished uphill.",
                           "“We had surprise,” Edric said.",
                           "“No. We had one child between us and a secret.”",
                           "“Now Ruk can prepare.”",
                           "“Good. If he prepares to talk, fewer people die. If he prepares to fight, we have learned what his promise is worth.”",
                           "Gongo watched him for a moment. “That was either diplomacy or a serious tactical error.”",
                           "“They overlap more than the manuals admit.”"
                       ]
    },
    {
        "act":  "Act III - Songs Beyond the Mountains",
        "title":  "Into the Listening Caves",
        "paragraphs":  [
                           "The storm reached Kettlehome before them.",
                           "They saw its effects along the upper road. A retaining wall had collapsed across one terrace, carrying young barley down the slope. Goats crowded beneath an overhang and refused to move even when Pip offered dried apple. Every few minutes, a vibration passed through the soles of Gobolin\u0027s boots. Loose stones chattered in place.",
                           "Lightning moved green inside the clouds, and every strike drew an answering chord from the mountains. At the eastern cleft, Sella waited with armed clansfolk.",
                           "She embraced Gobolin, inspected his borrowed lute, and struck Vaerith\u0027s treaty-ring with one fingernail.",
                           "“What did he fail to tell you?”",
                           "“Most things.”",
                           "“Good. You are learning his language.”",
                           "Sella then embraced Edric, surprising him into dropping his crutch, and thanked Moss for keeping her son alive. She knew their names from the copper-wing ravens. When Pip asked whether Vaerith had also reported their private conversations, Sella pointed toward three roasted birds cooling outside the cookhouse.",
                           "“Ravens can learn boundaries,” she said.",
                           "The council had divided. Some wanted Vaerith to burn the invaders regardless of the caves beneath their homes. Others wanted the dragon driven out. Ruk\u0027s agents promised freedom, trade, and the end of secrecy.",
                           "The division ran through families. Old Brik had carried a spear to the gatehouse and refused to stand beside his own daughter, who wanted Vaerith expelled. The copper workers feared losing the markets he had quietly arranged. Farmers remembered the three seasons when his presence kept hill raiders away. Younger goblins remembered chiefly that every road ended where the dragon preferred.",
                           "Gobolin spoke in the gate square. His first attempt failed. He began with the language he had prepared for Rivergate—rights, borders, lawful protection—and watched his uncle turn away. Those words described a world in which some distant authority had already agreed that Kettlehome mattered.",
                           "He stopped and began again. He told them what Merrow intended, what Vaerith had concealed, and which people from Rivergate had walked the first mile. He admitted that opening the valley might bring merchants they could not control and laws they had not written. He could promise neither safety nor gratitude.",
                           "“We will not choose between a dragon\u0027s cage and a merchant\u0027s chain,” he said. “Help us open the caves. Then stay above and protect our homes.”",
                           "No cheer followed. An aunt asked why they should trust the human guard. A smith demanded to know when Gobolin had learned about the mine. When he admitted it had been less than two weeks, someone called him Vaerith\u0027s fool. The word hurt because it was accurate.",
                           "Sella did not defend him. She asked the clans to vote on opening the sealed passage. The count took an hour and passed by eleven hands. Gobolin\u0027s speech had not decided them. The sight of Gongo\u0027s broken fingers and the testimony of the captured student\u0027s sister mattered more.",
                           "Sella took them through a bathhouse cellar into tunnels older than the clans. Pale swifts clicked overhead. The walls repeated whispers minutes after they were spoken.",
                           "At a fork, Gongo raised his bound hand. From the left came the memory of marching boots. From the right came a child\u0027s laughter preserved in stone.",
                           "Sella sang four notes.",
                           "The right-hand wall opened along a seam.",
                           "“The Kettle Song,” Gobolin said.",
                           "“Older than Kettlehome,” she replied. “We did not invent it. We remembered it.”",
                           "Behind the wall, stairs descended toward a red glow and the pulse of many voices singing one note."
                       ]
    },
    {
        "act":  "Act III - Songs Beyond the Mountains",
        "title":  "The Black Banner",
        "paragraphs":  [
                           "Ruk waited on a bridge spanning the central hollow. Black cloth hung from iron poles behind him. Below, hundreds of echo-iron veins glowed like buried strings.",
                           "He had grown lean. Three iron teeth pierced one ear.",
                           "When they were children, Ruk had always climbed first. He once crossed the steam channel on a fallen pine while Gobolin remained on the bank explaining why the trunk was unsafe. Ruk reached the far side, shouted that explanations did not shorten the distance, and crossed back to carry Gobolin\u0027s pack. Years later, after Vaerith punished a clan for trading without permission, they had argued in the same way. Ruk wanted to leave. Gobolin listed everything the valley might lose. Neither asked what exile would cost.",
                           "“Cousin,” Ruk said. “You finally left the dragon\u0027s garden.”",
                           "Black Banner archers surrounded the company. The three captured students knelt nearby. Lady Merrow was nowhere visible.",
                           "“She has gone below,” Ruk said. “When Vaerith kneels, the valley will be ours.”",
                           "“One of your raiders died at the lime quarry,” Gobolin said. “He asked me to tell you Merrow\u0027s people killed the cooper\u0027s boy. He said you had forbidden it.”",
                           "Ruk\u0027s face altered. Not surprise; confirmation.",
                           "“You knew she had broken your terms,” Gobolin said. “You stayed because admitting it would leave you with no victory to offer.”",
                           "“You stayed with Vaerith after he broke yours.”",
                           "“Yes.”",
                           "The answer removed the defense Gobolin had prepared. He had spent years giving the dragon\u0027s rule gentler names because Kettlehome was warm and fed. Ruk had given Merrow\u0027s betrayal the name of necessity because people followed him and needed their hunger to mean something.",
                           "“Merrow\u0027s contracts call your people expendable labor.”",
                           "“Human ink.”",
                           "“Human weapons. Human poison. Human promises.”",
                           "Ruk\u0027s smile broke. “And what did you bring? Human friends and the dragon\u0027s ring.”",
                           "He spoke of goblin tribes hunted from farms, children killed for bounties, and Vaerith choosing one valley to preserve while ignoring all beyond it. Every charge held truth. Behind Ruk, several archers lowered their eyes. They had not joined a mining concern. They had joined the promise of a place where goblin children could sleep without sentries. Merrow had understood that promise well enough to purchase it.",
                           "Gobolin removed the ring. “You are right about the cage. Wrong about the key.”",
                           "He tossed the ring into the hollow.",
                           "Gasps moved through both groups.",
                           "“I carry no dragon\u0027s seal,” Gobolin said. “I speak for Kettlehome because they heard me and chose to. Can Merrow say the same of you?”",
                           "A horn sounded below. Echo-iron answered, and Vaerith roared somewhere above the mountain.",
                           "Ruk\u0027s archers looked toward the sound.",
                           "Pip moved first. Her knife cut the students\u0027 rope. Moss struck a violent chord. Edric overturned an iron pole, and the bridge dissolved into confusion.",
                           "Ruk had already looked toward the freed students when an archer behind him drew on Pip. He shouted for the bow to lower. The archer fired anyway. Ruk knocked the shot aside with his forearm guard. The gesture split the Black Banner more effectively than a speech. Three goblins moved toward Ruk. Two kept their bows trained on Gobolin. The rest watched the lower stairs, waiting to learn which betrayal would prove survivable.",
                           "“If she lied,” Ruk said, “I kill her.”",
                           "“Get in line.”",
                           "Together they ran below."
                       ]
    },
    {
        "act":  "Act III - Songs Beyond the Mountains",
        "title":  "A Dragon in Chains",
        "paragraphs":  [
                           "The hollow chamber had been carved into an instrument. Iron ribs rose around a circular platform, each connected to a different vein in the rock. Gongo\u0027s stolen diagrams covered the floor, weighted by mining tools and blood-dark stones. Lady Merrow stood at their center in black gloves, singing Vaerith\u0027s hidden name while hired chanters repeated it.",
                           "Above them, the dragon hung in chains made of sound.",
                           "Each note tightened bands of green light around his wings and throat. Vaerith struck the cavern roof, showering stone, but could not breathe flame.",
                           "“Late, envoy,” Merrow called. Her voice sounded raw between repetitions. “Your teacher\u0027s work was excellent.”",
                           "“You burned caravans for a mine.”",
                           "“I lost a brother when a red dragon crossed the Lume. We had walls, soldiers, and treaties. None mattered. Your protector can destroy Rivergate before our warning bell finishes one stroke, and you ask us to trust his affection for you.”",
                           "The charge found the fear Gobolin had carried since childhood. “Then ask for safeguards. Ask for witnesses. You killed people so you could own the answer.”",
                           "“Ownership is a safeguard.”",
                           "“For the owner.”",
                           "“His early work,” Gongo said. “My later work concerns mistakes.”",
                           "He began a counter-note. The iron ribs shuddered. Merrow changed pitch, forcing him higher. His injured hand could not form the signs needed to guide the resonance.",
                           "Gobolin took up the travel lute.",
                           "“What do I play?”",
                           "“A pattern it has not stored,” Gongo said. “Once it learns the repetition, we lose the advantage.”",
                           "Merrow\u0027s system depended on a single voice copied perfectly. Gobolin answered with the Kettle Song, where no voice entered at the same time.",
                           "Sella took the second line. Moss added the river lament. Pip sang a tavern verse in a key that should have been illegal. Edric supplied the marching beat. Gongo threaded his counter-note through them.",
                           "Ruk gave the funeral response used by clans beyond the valley. Two Black Banner archers answered from habit, then glanced at each other. The students followed Gongo\u0027s hand. Their combined song wandered whenever fear made someone hurry, and the echo-iron began to learn it. Gongo changed the entrance. Sella changed it again. Each singer had to listen rather than merely repeat.",
                           "Cracks opened in the glowing chains.",
                           "Merrow drew a knife and lunged for Gobolin. Ruk intercepted her. The blade entered beneath his ribs.",
                           "Vaerith\u0027s bonds broke.",
                           "The dragon fell onto the platform between Merrow and everyone she had betrayed.",
                           "He inhaled.",
                           "“No!” Gobolin\u0027s shout crossed the music.",
                           "Vaerith\u0027s fire gathered behind his teeth.",
                           "“If you burn her now, they will call this dragon justice forever.”",
                           "The flame faded slowly.",
                           "Vaerith pinned Merrow beneath one claw. “Little ambassador,” he said, voice shaking the chamber, “your plan is excessively expensive.”",
                           "“Send me the bill.”"
                       ]
    },
    {
        "act":  "Act III - Songs Beyond the Mountains",
        "title":  "The Song Without an Owner",
        "paragraphs":  [
                           "Breaking the chains had awakened the mine.",
                           "Every vein repeated the last song, louder each time. Stone split overhead. The hollow would collapse and take half the valley with it.",
                           "Gongo understood first. “The resonance needs somewhere to go.”",
                           "Vaerith could carry it upward, but the force might tear his wings. The iron ribs could direct it, but only if voices held the counter-pattern from inside the chamber.",
                           "“No,” Sella said when Gobolin stepped onto the platform.",
                           "“I am not the treaty,” he told her. “I am not the bridge. I am a singer. This part is mine.”",
                           "He began the road song.",
                           "One mile for the promise.",
                           "One mile for the fear.",
                           "The others refused to leave. Pip added Rivergate\u0027s verse. Moss laid the river beneath it. Edric sang of a gate opening. Ruk, pale from blood loss, contributed a Black Banner funeral line. Sella returned the four notes that had begun Gobolin\u0027s journey.",
                           "Gongo conducted with his unbroken hand.",
                           "Vaerith rose through the central shaft, carrying the accumulating chord. Light poured along his scales. At the summit he opened his wings, and the mountain released its stored voices into the storm.",
                           "Across the valley, every bell rang. The rain hung silver in the white light. Then the mountain released generations of work songs, arguments, lullabies, and names in a single wave that rolled beyond the peaks.",
                           "The iron went dark.",
                           "Vaerith landed badly on the upper terrace. One wing hung torn, but he lived.",
                           "When the echoes faded, nobody could say who had written the song they had sung.",
                           "“Good,” Gongo said. “Ownership would ruin it.”"
                       ]
    },
    {
        "act":  "Act III - Songs Beyond the Mountains",
        "title":  "The Treaty at Dawn",
        "paragraphs":  [
                           "They negotiated in the gate square beneath a clear sky.",
                           "Duchess Elira arrived with Captain Tern and enough guards to arrest Merrow without pretending it was a request. Representatives of Kettlehome\u0027s clans sat opposite Rivergate\u0027s council. Black Banner survivors stood between, unclaimed by either side.",
                           "Vaerith watched from the gatehouse, bandaged and silent. Others spoke without waiting for his permission.",
                           "The first treaty failed before breakfast. Rivergate demanded inspection rights. Kettlehome demanded recognition of every mountain path as sovereign ground. Ruk demanded land for the displaced. Merchants demanded ore. Sella demanded better tea.",
                           "The second treaty failed over the meaning of defensive force. The third lasted until afternoon. Vaerith rejected any clause that named him subject to a joint council. The miller refused a border that Rivergate surveyors had not walked. Ruk would not disarm while human patrols retained crossbows. Voices rose until the delegates were speaking only to those already on their side.",
                           "Gobolin felt the old reflex: find the sentence that would make them approve of him and call the approval peace. He set down his pen instead. The meeting stopped because the envoy had stopped pretending he could reconcile incompatible demands by sounding reasonable.",
                           "They broke into smaller tables. Sella and the miller marked the watercourses each community actually used. Nessa and Ruk listed weapons both mixed patrols would surrender at the gate. Gongo drafted an echo-iron clause, then made a student rewrite it so ordinary readers could understand the danger. Vaerith withdrew to the gatehouse and returned only after Kettlehome\u0027s elders reminded him that he had no signature to withhold.",
                           "The fourth version survived.",
                           "Rivergate recognized Kettlehome\u0027s valley and guest-law. Kettlehome opened one trade road and accepted mixed patrols chosen by both communities. Black Banner families willing to surrender raiding claims received terrace land under the same law as any clan. Echo-iron extraction was forbidden for ten years and afterward required unanimous consent from a joint council. Vaerith surrendered unilateral authority over entry to the valley.",
                           "“I surrender nothing,” the dragon said.",
                           "“Then the treaty records that you magnificently chose restraint,” Gobolin replied.",
                           "Vaerith considered this. “Acceptable.”",
                           "Lady Merrow was taken west for trial. Ruk survived and refused to thank anyone. Edric received his badge from Captain Tern and pinned it on only after Nessa joined the first mixed patrol.",
                           "At sunrise, Gobolin signed for Kettlehome. His hand shook.",
                           "Sella placed hers over it. “A treaty is not peace.”",
                           "“I know.”",
                           "“Good. Peace is what we do tomorrow.”"
                       ]
    },
    {
        "act":  "Act III - Songs Beyond the Mountains",
        "title":  "Beyond the Mountains",
        "paragraphs":  [
                           "By midsummer, the road had acquired milestones.",
                           "Human wagons brought grain, books, and tools. Goblin carts carried copper kettles, steam-moss, and cloth whose makers had learned that human buyers would pay twice as much for anything described as authentically secret.",
                           "Arguments multiplied with commerce. So did marriages, debts, recipes, and songs.",
                           "Ruk supervised new terraces for Black Banner families and complained that peace involved more digging than war. Vaerith recovered on a sun-warmed ridge and offered frequent, unsolicited advice. His ravens continued to observe everything, but now children threw them crumbs and demanded reports in return.",
                           "Gobolin returned to Rivergate wearing a new mandolin made by Kettlehome and human craftspeople together. The Golden Harp\u0027s door stood open.",
                           "Gongo waited in the teaching room. “Your song has an ending?”",
                           "“No.”",
                           "The gnome raised an eyebrow.",
                           "“It has a place to continue.”",
                           "Gongo held out a brass student token. “Your right hand still rushes.”",
                           "Gobolin accepted it. “My teacher is severe.”",
                           "“Your teacher has standards.”",
                           "He would study one season in Rivergate and travel the next as Kettlehome\u0027s cultural envoy. The arrangement contained too many council meetings and less applause than he had once imagined. He had chosen it himself.",
                           "That evening, he played at the Bent Nail. Moss joined on viol. Pip arrived late through a window despite the unlocked door. Edric sang badly and with conviction. The cooper\u0027s widow supplied the verse about those whose names had been hidden beneath the language of trade.",
                           "Humans and goblins filled the room. Some listened with arms crossed, and many knew only their own verses. They argued over the proper rhythm between songs.",
                           "Gobolin remembered the morning he left home, when the mountain returned every sound except the one he wanted. He had been waiting for his mother\u0027s voice to come back unchanged. Songs did not do that. They crossed a distance and came back carrying other voices.",
                           "He played the road melody.",
                           "One mile for the promise.",
                           "One mile for the fear.",
                           "One mile for the stranger",
                           "who chose to call you near.",
                           "The room answered.",
                           "Beyond Rivergate, beyond Kettlehome, beyond the copper dragon sleeping beneath the summer stars, the road continued into country no treaty had named.",
                           "And the song went with it."
                       ]
    }
];
